baseURL = "https://hungry-wozniak-e915f8.netlify.com" #"./"
#relativeURLs = true #https://gohugo.io/content-management/urls/#relative-urls
#title = "Minimo"
#https://discourse.gohugo.io/t/howto-convert-your-front-matter-from-toml-to-yaml/332

theme = "minimo"

googleAnalytics = ""

Paginate = 99
preserveTaxonomyNames = true

#enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Minimalist theme for Hugo"
title404 = "Simplicity is the ultimate"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]

[params.copyright]
prefix = ""
holder = "Author"
startYear = "2019"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
#hideEntryNavigation = ["page"] # boolean / array of sections
#hideEntryMeta = ["page"] # boolean / array of sections
#showReadingTime = true
#showLastmod = true
#taxonomyCloudShuffle = true
accentColor = "firebrick"
#hideMainMenu = false


[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[params.social]
#codepen = "Author"
email = "alan.scott.phillips@pm.me"
#github = "Author"
#linkedin = "Author"
twitter = "Author"
youtube = "UCH4BJzkxRkXL-ATLR9YutiA"#Author


[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/MunifTanjim/minimo"

[blackfriday]
hrefTargetBlank = true

#[languages]
# edit this block for your own language

#[languages.en]
#lang = "en"
#languageName = "English"
#weight = 1
