baseurl = "https://hungry-wozniak-e915f8.netlify.com" #{{ .Site.BaseURL }} "/" && netlify "./" local only
#relativeURLs = "true"

languageCode = "en-gb" #Initial configuration reset
title = "Inspired Labs"
#disableKinds = ["home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]#"page",
#theme = "ultimate-simplicity"
#theme = "ga-hugo-theme"
## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  key = "value"

[Params]
  [[Params.description]]
    description = "Scott Phillips is a Designer & Frontend Developer"

  [[Params.assignment]]
    assignment = "Designer & Frontend Developer"

  [[Params.location]]
    location = "Oxford"


  [[Params.links]]
    title = "Email"
    url = "mailto:alan.scott.phillips@pm.me"
